server:
  port: 9006
eureka:
  client:
    service-url:
      defaultZone: http://huangwena:8761/eureka,http://huangwenb:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
# 配置熔断策略
  #springboot中暴露健康检查等断点接⼝
spring:
  application:
    name: huangwen-cloud-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hw1197328718/huangwen-cloud-configserver.git #配置git服务地址
          username: hw1197328718 #配置git用户名
          password: 520168hw #配置git密码
          search-paths:
          - huangwen-cloud-configserver
      # 读取分支
      label: master
management:
 endpoints:
  web:
   exposure:
    include: "*"
# 暴露健康接⼝的细节
 endpoint:
  health:
   show-details: always
